name: buf-pull-request
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
        github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     input: "proto"
      #     # The 'main' branch of the GitHub repository that defines the module.
      #     against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "proto"
          buf_token: ${{ secrets.BUF_TOKEN_MIKANA0918 }}
